name: "❓ Question"
description: Ask anything about eslint-plugin-awscdk
title: "(your question)"
labels: [question]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        👋 Welcome! Feel free to ask any questions about eslint-plugin-awscdk!

        Examples of questions:
        - How do I configure eslint.config.js?
        - Why is this rule not working?
        - What's the best way to set up the plugin?
        - How do I fix this error?

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        If applicable, add:
        - Code snippets
        - Configuration files
        - Error messages
      placeholder: |
        ```js
        // Example: Your current configuration or code
        export default [
          {
            plugins: {
              cdk: cdkPlugin
            },
            rules: {
              // ...
            }
          }
        ]
        ```
    validations:
      required: false

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of eslint-plugin-awscdk are you using?
      placeholder: "1.0.0"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Quick Check
      options:
        - label: I've checked the [documentation](https://eslint-plugin-awscdk.dev)
          required: false
        - label: I've searched for similar questions
          required: false
